apiVersion: apps/v1
kind: Deployment
metadata:
  name: aslideal-backend
  labels:
    app: aslideal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aslideal
  template:
    metadata:
      labels:
        app: aslideal
    spec:
      containers:
      - name: backend
        image: your-docker-repo/aslideal-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database_url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis_url
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"