apiVersion: v1
kind: Service
metadata:
  name: aslideal-service
  labels:
    app: aslideal
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: aslideal