version: '3.8'

services:
  backend:
    image: "${IMAGE_FULL:-aslideal/backend:latest}"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-aslideal}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
